# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75ce06211b09f8b0b55ce65ab9febc8c2fa598806380067b381f31055dafa037ab279cf35e406fe947e1a4eca2ab880d45acbdcacaa921213f5f5ea0a6ee155e

test:
  secret_key_base: 3a9736fa64cf44cb95793aabcb7b157853d5cf2e29481de68ad4b2567cbcb9d0ff6ea2d94bdcafd13d986252443ac364b0bdda002f396f0ee49a8f73ae8cddaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
